language: php
dist: trusty
sudo: false

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - php -m

script:
  - ./test/syntax.sh
